version: '3'

services:
  nginx:
    image: nginx:1.20.1-alpine
    container_name: nginx
    volumes:
      - ./application:/html:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./secret:/etc/ssl/nomenclature:ro
      - ./mime.types:/etc/nginx/mime.types
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    links:
      - php
  redis:
    image: redis:7.0
    container_name: redis
    expose:
      - "6379"
  php:
    container_name: php
    build:
      context: .
      dockerfile: ./conf/php/PHP.Dockerfile
    environment:
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_DATABASE
        - MYSQL_NAME
        - MYSQL_PORT
        - MAILGUN_API_ENDPOINT
        - MAILGUN_API_KEY
        - DOMAIN
        - ADDRESS_SALT
    volumes:
      - ./application:/html:ro
      - ./downloads:/var/www/downloads:ro
      - /etc/localtime:/etc/localtime:ro
    links:
      - mysql
      - redis
  mysql:
    image: mariadb:10.6.3
    container_name: database
    environment:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_DATABASE
    volumes:
      - mysqldata:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - ./sqlinit:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
volumes:
  mysqldata: {}
